[package]
name = "ap-storage-partition"
description = "MBR Partition support."
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/alpico/storage.pico"

[dependencies]
ap-storage = { path = "../ap-storage"}
ap-util-slice-writer = { path = "../ap-util-slice-writer"}