[package]
name = "ap-util-slice-writer"
description = "Write into a slice of bytes while truncating on overflow."
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/alpico/storage.pico"

[dependencies]
