[package]
name = "ap-storage"
description = "The alpico storage interfaces."
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/alpico/storage.pico"

[dependencies]
ap-util-attr = { path = "../ap-util-attr" }
anyhow = { version = "1", default-features = false }


