[package]
name = "ap-storage-vfat"
description = "On-disk structures of the FAT filesystems."
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/alpico/storage.pico"

[dependencies]
ap-util-date = { path="../ap-util-date" }


[features]
fat-plus = []