[package]
name = "ap-storage-vfat-mkfs"
description = "Make a FAT filesystem."
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/alpico/storage.pico"

[dependencies]
ap-storage={ path = "../ap-storage"}
ap-storage-vfat={ path = "../ap-storage-vfat"}
