[package]
name = "ap-storage-vfat-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
ap-storage-vfat={ path = "../ap-storage-vfat"}
ap-storage-vfat-mkfs={ path = "../ap-storage-vfat-mkfs"}
