name: Run Script

on: [issues, issue_comment]

jobs:
  build:
    uses: alpico/workflows/.github/workflows/notion_bridge.yml@main
    with:
      page: "d3da9e0533c94f78abfb81616c44b063"
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      notion_api_key: ${{ secrets.NOTION_API_KEY }}
